### ISSUE TITLE
hw5 grade

### ISSUE THREAD

**Issue by dcjones** [nghitrampham/CSE583_FinalProject#1]
~~The functional specification looks good, but the components specification is missing.~~

~~4/7 points~~

**Comment by nghitrampham** [comment]
We had it there in the same documentation, it is right after the functional specification

**Comment by dcjones** [comment]
My mistake! I was expecting another file. This looks good.

7/7 points

**Comment by nghitrampham** [comment]
Sorry about that Daniel, we will make it two files next time!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
